vid = []

[[switch]]
active_level_duration = "2s"
id = 1

[[switch]]
active_level_duration = "2s"
id = 2

[[vbu]]
id = 1
unique_address = "C4:21:CB:09:B6:09"
x = 1
y = 1.5
z = 0.4

[[vbu]]
id = 2
unique_address = "D4:6E:E9:D0:53:79"
x = -1
y = -1.5
z = 0.4

[[vbu]]
id = 3
unique_address = "F8-F4-9B-91-CE-38"
x = 1
y = -1.5
z = 0.4

[[vbu]]
id = 4
unique_address = "d8-68-ec-21-f5-e0"
x = -1
y = 1.5
z = 0.4

[[vbu]]
id = 5
unique_address = "11-11-11-11-11-11"
x = 4
y = 4
z = 0

[[vod]]
angle = 0
around_the_corner_blinking = false
around_the_corner_light_level = 20
display_brightness = 100
display_brightness_auto_tuning = true
measurement_lifetime = "2s"
sound_volume = 100
sound_volume_auto_tuning = true
status_update_interval = "100ms"
tag_in_cabin_pathloss = 75
unique_address = "c4-38-45-71-1c-cc"
x = 0
y = 0

[[zone]]
id = 1
level = "Danger"
points = [[-4.54, 11.23], [4.54, 11.23], [5.5, 4.65], [5.5, -4.65], [4.54, -11.23], [-4.54, -11.23], [-5.5, -4.65], [-5.5, 4.65]]

[[zone]]
id = 2
level = "Alert"
points = [[-8.68, 20.46], [8.68, 20.46], [4.54, 11.23], [-4.54, 11.23], [-8.68, 20.46]]

[[zone]]
id = 3
level = "Alert"
points = [[8.68, 20.46], [14.74, 8.48], [5.5, 4.65], [4.54, 11.23], [8.68, 20.46]]

[[zone]]
id = 4
level = "Alert"
points = [[14.74, 8.48], [14.74, -8.48], [5.5, -4.65], [5.5, 4.65], [14.74, 8.48]]

[[zone]]
id = 5
level = "Alert"
points = [[14.74, -8.48], [6.61, -20.46], [4.54, -11.23], [5.5, -4.65], [14.74, -8.48]]

[[zone]]
id = 6
level = "Alert"
points = [[6.61, -20.46], [-6.61, -20.46], [-4.54, -11.23], [4.54, -11.23], [6.61, -20.46]]

[[zone]]
id = 7
level = "Alert"
points = [[-6.61, -20.46], [-14.74, -8.48], [-5.5, -4.65], [-4.54, -11.23], [-6.61, -20.46]]

[[zone]]
id = 8
level = "Alert"
points = [[-14.74, -8.48], [-14.74, 8.48], [-5.5, 4.65], [-5.5, -4.65], [-14.74, -8.48]]

[[zone]]
id = 9
level = "Alert"
points = [[-14.74, 8.48], [-8.68, 20.46], [-4.54, 11.23], [-5.5, 4.65], [-14.74, 8.48]]

[events]
precise_location = false
presence_detection = true
zones = ["A", "E", "I"]

[journal]
precise_location = false
presence_detection = false
zones = []

[system]
register_address_lifetime = "1h"
register_request_cooldown = "100ms"
subghz_freq = 872
supported_versions = []
tags_visibility_lifetime = "5s"
uwb_mode = 3
v2v_visibility_disabled = false
vcu_visibility_lifetime = "5s"
[[tags.notification_settings]]
lamp_cycles = 2
status_code = 10
time_lamp_off = 3
time_lamp_on = 3
time_vibration_off = 1
time_vibration_on = 1
vibration_cycles = 5

[[tags.notification_settings]]
lamp_cycles = 5
status_code = 20
time_lamp_off = 1
time_lamp_on = 1
time_vibration_off = 3
time_vibration_on = 3
vibration_cycles = 2

[vcu]
check_location_expire_interval = "100ms"
command_timeout_handicap = "2ms"
location_max_lifetime = "2s"
long_range_location_pathloss_deviation = 4
long_range_location_vbus = []
passive_measurement_additional_timeout = "14ms"
presence_lifetime = "2s"
synchro_cycle_interval = "200ms"
unique_id = 1

[vcu.person_locating_filter]
acceleration_noise_x = 0.8
acceleration_noise_y = 0.8
anchor_measurement_noise = 0.3
init_position_noise_x = 1
init_position_noise_y = 1
init_velocity_noise_x = 1
init_velocity_noise_y = 1
max_allowed_measurement_distance = 50
max_inner_circle_distance = 1

[vcu.vehicle_locating_filter]
acceleration_noise_x = 0.8
acceleration_noise_y = 0.8
anchor_measurement_noise = 0.3
init_position_noise_x = 1
init_position_noise_y = 1
init_velocity_noise_x = 1
init_velocity_noise_y = 1
max_allowed_measurement_distance = 50
max_inner_circle_distance = 1

[visual_configurator]
language = "ru"
transport_size_length = 3
transport_size_width = 2

[visual_configurator.previous_config_version]
vid = []

[[visual_configurator.previous_config_version.vbu]]
id = 1
unique_address = "C4:21:CB:09:B6:09"
x = 1
y = 1.5
z = 0.4

[[visual_configurator.previous_config_version.vbu]]
id = 2
unique_address = "D4:6E:E9:D0:53:79"
x = -1
y = -1.5
z = 0.4

[[visual_configurator.previous_config_version.vbu]]
id = 3
unique_address = "F8-F4-9B-91-CE-38"
x = 1
y = -1.5
z = 0.4

[[visual_configurator.previous_config_version.vbu]]
id = 4
unique_address = "d8-68-ec-21-f5-e0"
x = -1
y = 1.5
z = 0.4

[[visual_configurator.previous_config_version.vbu]]
id = 5
unique_address = "11-11-11-11-11-11"
x = 4
y = 4
z = 0

[[visual_configurator.previous_config_version.vod]]
angle = 0
around_the_corner_blinking = false
around_the_corner_light_level = 20
display_brightness = 100
display_brightness_auto_tuning = true
measurement_lifetime = "2s"
sound_volume = 100
sound_volume_auto_tuning = true
status_update_interval = "100ms"
tag_in_cabin_pathloss = 75
unique_address = "c4-38-45-71-1c-cc"
x = 0
y = 0

[[visual_configurator.previous_config_version.zone]]
id = 1
level = "Danger"
points = [[-4.54, 11.23], [4.54, 11.23], [5.5, 4.65], [5.5, -4.65], [4.54, -11.23], [-4.54, -11.23], [-5.5, -4.65], [-5.5, 4.65]]

[[visual_configurator.previous_config_version.zone]]
id = 2
level = "Alert"
points = [[-8.68, 20.46], [8.68, 20.46], [4.54, 11.23], [-4.54, 11.23], [-8.68, 20.46]]

[[visual_configurator.previous_config_version.zone]]
id = 3
level = "Alert"
points = [[8.68, 20.46], [14.74, 8.48], [5.5, 4.65], [4.54, 11.23], [8.68, 20.46]]

[[visual_configurator.previous_config_version.zone]]
id = 4
level = "Alert"
points = [[14.74, 8.48], [14.74, -8.48], [5.5, -4.65], [5.5, 4.65], [14.74, 8.48]]

[[visual_configurator.previous_config_version.zone]]
id = 5
level = "Alert"
points = [[14.74, -8.48], [6.61, -20.46], [4.54, -11.23], [5.5, -4.65], [14.74, -8.48]]

[[visual_configurator.previous_config_version.zone]]
id = 6
level = "Alert"
points = [[6.61, -20.46], [-6.61, -20.46], [-4.54, -11.23], [4.54, -11.23], [6.61, -20.46]]

[[visual_configurator.previous_config_version.zone]]
id = 7
level = "Alert"
points = [[-6.61, -20.46], [-14.74, -8.48], [-5.5, -4.65], [-4.54, -11.23], [-6.61, -20.46]]

[[visual_configurator.previous_config_version.zone]]
id = 8
level = "Alert"
points = [[-14.74, -8.48], [-14.74, 8.48], [-5.5, 4.65], [-5.5, -4.65], [-14.74, -8.48]]

[[visual_configurator.previous_config_version.zone]]
id = 9
level = "Alert"
points = [[-14.74, 8.48], [-8.68, 20.46], [-4.54, 11.23], [-5.5, 4.65], [-14.74, 8.48]]

[visual_configurator.previous_config_version.events]
precise_location = false
presence_detection = true
zones = ["A", "E", "I"]

[visual_configurator.previous_config_version.journal]
precise_location = false
presence_detection = false
zones = []

[visual_configurator.previous_config_version.system]
register_address_lifetime = "1h"
register_request_cooldown = "100ms"
subghz_freq = 872
supported_versions = []
tags_visibility_lifetime = "5s"
uwb_mode = 3
v2v_visibility_disabled = false
vcu_visibility_lifetime = "5s"
[[visual_configurator.previous_config_version.tags.notification_settings]]
lamp_cycles = 2
status_code = 10
time_lamp_off = 3
time_lamp_on = 3
time_vibration_off = 1
time_vibration_on = 1
vibration_cycles = 5

[[visual_configurator.previous_config_version.tags.notification_settings]]
lamp_cycles = 5
status_code = 20
time_lamp_off = 1
time_lamp_on = 1
time_vibration_off = 3
time_vibration_on = 3
vibration_cycles = 2

[visual_configurator.previous_config_version.vcu]
check_location_expire_interval = "100ms"
command_timeout_handicap = "2ms"
location_max_lifetime = "2s"
long_range_location_pathloss_deviation = 4
long_range_location_vbus = []
passive_measurement_additional_timeout = "14ms"
presence_lifetime = "2s"
synchro_cycle_interval = "200ms"
unique_id = 1

[visual_configurator.previous_config_version.vcu.person_locating_filter]
acceleration_noise_x = 0.8
acceleration_noise_y = 0.8
anchor_measurement_noise = 0.3
init_position_noise_x = 1
init_position_noise_y = 1
init_velocity_noise_x = 1
init_velocity_noise_y = 1
max_allowed_measurement_distance = 50
max_inner_circle_distance = 1

[visual_configurator.previous_config_version.vcu.vehicle_locating_filter]
acceleration_noise_x = 0.8
acceleration_noise_y = 0.8
anchor_measurement_noise = 0.3
init_position_noise_x = 1
init_position_noise_y = 1
init_velocity_noise_x = 1
init_velocity_noise_y = 1
max_allowed_measurement_distance = 50
max_inner_circle_distance = 1

[visual_configurator.previous_config_version.visual_configurator]
language = "ru"
transport_size_length = 3
transport_size_width = 2
